In [2]:
import numpy as np

In [3]:
# 1D array
np.array([1,2,3])

array([1, 2, 3])

In [8]:
# 2D array
np.array([[1,2], [3,4]], dtype= 'int8')

array([[1, 2],
       [3, 4]], dtype=int8)

In [9]:
# 3D array 
np.array([[[1,2,3], [4,5,6]], [[5,6,7], [8,9,10]]], dtype = 'float64')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 5.,  6.,  7.],
        [ 8.,  9., 10.]]])

In [13]:
# extract specific item
x = np.array([[1,2], [3,4], [5,6], [7,8]])
x[:,1]

array([2, 4, 6, 8])

In [17]:
# 3D array 
y = np.array([[[1,2,3], [4,5,6]], [[5,6,7], [8,9,10]]])
y[:,1,:]

array([[ 4,  5,  6],
       [ 8,  9, 10]])